<a href="https://colab.research.google.com/github/Shubham-Das-Coder/Mathematics_For_Machine_Learning/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing the libraries
import numpy as np

In [2]:
#Creating a matrix using numpy
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
#Displaying the shape of the matrix
matrix_1.shape

(2, 2)

In [4]:
#Creating a matrix using numpy
matrix_2=np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
#Displaying the shape of the matrix
matrix_2.shape

(3, 3)

In [6]:
#Creating matrices with random floating values
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.11767276 0.9207928  0.59001137]
 [0.07722631 0.09328821 0.94160468]
 [0.98133921 0.38639879 0.36791287]]


In [7]:
#Creating matrices with random integer values
random_integer_matrix=np.random.randint(100,size=(4,4))
print(random_integer_matrix)

[[72 55 17 84]
 [91 85 69 11]
 [66 94 82 24]
 [67 40 64 82]]


In [8]:
#Matrix with all the values as 1
matrix_with_ones=np.ones((3,4))
print(matrix_with_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#Matrix with all the values as 1
matrix_with_ones_2=np.ones((4,3),dtype=int)
print(matrix_with_ones_2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
#Null matrix or zero matrix
null_matrix=np.zeros((5,5))
print(null_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#Identity matrix
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Transpose of a matrix
a=np.random.randint(100,size=(4,4))
print(a)
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[10 55 61 74]
 [40 89 58 78]
 [94 37 88 47]
 [82 37 32 82]]
[[10 40 94 82]
 [55 89 37 37]
 [61 58 88 32]
 [74 78 47 82]]


In [13]:
#Transpose of a matrix
b=np.random.randint(100,size=(3,4))
print(b)
transpose_of_b=np.transpose(b)
print(transpose_of_b)

[[93 55 16 28]
 [58 41 83 68]
 [ 3  6 33 35]]
[[93 58  3]
 [55 41  6]
 [16 83 33]
 [28 68 35]]


In [14]:
#Addition of matrices
A=np.array([[2,3],[4,5]])
print(A)
B=np.array([[6,7],[8,9]])
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [15]:
A.shape
B.shape

(2, 2)

In [16]:
sum=A+B
print(sum)

[[ 8 10]
 [12 14]]


In [17]:
#Creating two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))

In [18]:
print(matrix_1)

[[8 2 2]
 [9 9 1]
 [7 3 8]]


In [19]:
print(matrix_2)

[[1 2 9]
 [1 2 0]
 [4 6 2]]


In [20]:
sum=np.add(matrix_1,matrix_2)
print(sum)

[[ 9  4 11]
 [10 11  1]
 [11  9 10]]


In [21]:
#Subtraction of two matrices
A=np.array([[5,6],[7,8]])
B=np.array([[1,2],[3,4]])
print(A)
print(B)

[[5 6]
 [7 8]]
[[1 2]
 [3 4]]


In [22]:
difference=A-B
print(difference)

[[4 4]
 [4 4]]


In [23]:
#Creating two matrices with random values
matrix1=np.random.randint(10,size=(3,3))
matrix2=np.random.randint(10,size=(3,3))

In [24]:
print(matrix1)
print(matrix2)

[[4 4 2]
 [5 5 9]
 [8 8 5]]
[[7 1 3]
 [0 7 5]
 [6 1 4]]


In [25]:
diff=np.subtract(matrix1,matrix2)
print(diff)

[[-3  3 -1]
 [ 5 -2  4]
 [ 2  7  1]]


In [26]:
#Multiplying a matrix by a scalar
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[2 5 8 3]
 [7 9 2 5]
 [3 7 8 1]
 [6 2 2 4]]


In [27]:
product=np.multiply(x,y)
print(product)

[[10 25 40 15]
 [35 45 10 25]
 [15 35 40  5]
 [30 10 10 20]]


In [28]:
#Multiplying 2 matrices
Matrix_1=np.random.randint(5,size=(3,3))
Matrix_2=np.random.randint(5,size=(3,4))
print(Matrix_1)
print(Matrix_2)

[[4 2 3]
 [4 3 3]
 [0 2 0]]
[[3 1 0 4]
 [0 2 1 3]
 [4 0 0 0]]


In [29]:
prod=np.dot(Matrix_1,Matrix_2)
print(prod)

[[24  8  2 22]
 [24 10  3 25]
 [ 0  4  2  6]]


In [30]:
prod.shape

(3, 4)

In [31]:
#Multiplying 2 matrices
Matrix_1=np.random.randint(5,size=(3,3))
Matrix_2=np.random.randint(5,size=(3,3))
print(Matrix_1)
print(Matrix_2)

[[0 3 4]
 [1 2 4]
 [0 0 4]]
[[4 0 0]
 [0 0 4]
 [0 3 0]]


In [32]:
prod=np.dot(Matrix_1,Matrix_2)
print(prod)

[[ 0 12 12]
 [ 4 12  8]
 [ 0 12  0]]


In [33]:
prod.shape

(3, 3)

In [34]:
mat_1=np.random.randint(5,size=(3,3))
mat_2=np.random.randint(5,size=(3,3))
print(mat_1)
print(mat_2)

[[3 1 2]
 [2 1 4]
 [4 3 2]]
[[1 3 0]
 [4 3 0]
 [0 1 3]]


In [35]:
mult=np.multiply(mat_1,mat_2)
print(mult)

[[3 3 0]
 [8 3 0]
 [0 3 6]]


In [36]:
mult.shape

(3, 3)